const cats=['Blank','Protein','Carb','Fat','Vegetable','Fruit','Dairy','Other'];
let foods=[
{name:'None / Blank',cat:'Blank',cal:0,p:0,c:0,f:0,sod:0,sugar:0,serv:100},
{name:'Chicken Breast Raw',cat:'Protein',cal:120,p:23,c:0,f:2.6,sod:60,sugar:0,serv:100},
{name:'Lean Ground Beef 93%',cat:'Protein',cal:172,p:21,c:0,f:8,sod:75,sugar:0,serv:100},
{name:'Salmon',cat:'Protein',cal:208,p:20,c:0,f:13,sod:59,sugar:0,serv:100},
{name:'Egg Whites',cat:'Protein',cal:52,p:11,c:.7,f:.2,sod:166,sugar:.7,serv:100},
{name:'Greek Yogurt Nonfat',cat:'Dairy',cal:59,p:10,c:3.6,f:.4,sod:36,sugar:3.2,serv:170},
{name:'White Rice Cooked',cat:'Carb',cal:130,p:2.7,c:28,f:.3,sod:1,sugar:.1,serv:100},
{name:'Sweet Potato',cat:'Carb',cal:86,p:1.6,c:20,f:.1,sod:55,sugar:4.2,serv:100},
{name:'Oats',cat:'Carb',cal:389,p:17,c:66,f:7,sod:2,sugar:1,serv:40},
{name:'Banana',cat:'Fruit',cal:89,p:1.1,c:23,f:.3,sod:1,sugar:12,serv:118},
{name:'Avocado',cat:'Fat',cal:160,p:2,c:9,f:15,sod:7,sugar:.7,serv:100},
{name:'Peanut Butter',cat:'Fat',cal:588,p:25,c:20,f:50,sod:17,sugar:9,serv:32},
{name:'Olive Oil',cat:'Fat',cal:884,p:0,c:0,f:100,sod:2,sugar:0,serv:14},
{name:'Broccoli',cat:'Vegetable',cal:35,p:2.4,c:7.2,f:.4,sod:41,sugar:1.4,serv:100},
{name:'Spinach',cat:'Vegetable',cal:23,p:2.9,c:3.6,f:.4,sod:79,sugar:.4,serv:100}
].sort((a,b)=>a.cat.localeCompare(b.cat)||a.name.localeCompare(b.name));
const state={meals:Array.from({length:6},()=>Array.from({length:7},()=>({cat:'Blank',food:'None / Blank',qty:0,unit:'g'})))};
const $=id=>document.getElementById(id); const num=id=>parseFloat($(id).value)||0;
function bmr(){const w=num('weight')*.453592,h=num('height')*2.54,a=num('age');return $('sex').value==='Male'?10*w+6.25*h-5*a+5:10*w+6.25*h-5*a-161}
function targets(){const base=bmr(), t=base*parseFloat($('activity').value), diff=num('goalWeight')-num('weight'), weekly=diff/(num('weeks')||1);let cal=t; const g=$('goal').value;if(g==='Fat Loss')cal=t-500;if(g==='Lean Bulk')cal=t+250;if(g==='Muscle Gain')cal=t+400;if(g==='Recomp')cal=t-150;if(g==='Maintain')cal=t; $('bmr').textContent=Math.round(base);$('tdee').textContent=Math.round(t);$('targetCalories').textContent=Math.round(cal);$('weeklyChange').textContent=weekly.toFixed(2)+' lb/wk';$('proteinTarget').value=$('proteinTarget').value||Math.round(num('weight')*1);$('fatTarget').value=$('fatTarget').value||Math.round(num('weight')*.35);$('carbTarget').value=$('carbTarget').value||Math.max(0,Math.round((cal-(num('proteinTarget')*4+num('fatTarget')*9))/4));$('goalStatus').textContent=Math.abs(weekly)>2?'Aggressive pace: consider extending timeframe or adjusting calories.':'Pace looks reasonable for most clients if adherence, recovery, and health markers are good.';return cal}
function grams(q,u,food){if(u==='oz')return q*28.3495;if(u==='serving')return q*(food.serv||100);return q}
function calcRow(r){const food=foods.find(f=>f.name===r.food)||foods[0]; const g=grams(parseFloat(r.qty)||0,r.unit,food); const m=g/100; return {cal:food.cal*m,p:food.p*m,c:food.c*m,f:food.f*m,sod:(food.sod||0)*m,sugar:(food.sugar||0)*m,grams:g}}
function foodOptions(cat,selected){return foods.filter(f=>cat==='Blank'?f.cat==='Blank':f.cat===cat).sort((a,b)=>a.name.localeCompare(b.name)).map(f=>`<option ${f.name===selected?'selected':''}>${f.name}</option>`).join('')}
function renderMeals(){const wrap=$('meals');wrap.innerHTML='';state.meals.forEach((meal,mi)=>{const div=document.createElement('div');div.className='meal';div.innerHTML=`<h3>Meal ${mi+1}</h3><table><thead><tr><th>Category</th><th>Food</th><th>Qty</th><th>Unit</th><th>Calories</th><th>Protein</th><th>Carbs</th><th>Fat</th></tr></thead><tbody>${meal.map((r,ri)=>{const m=calcRow(r);return `<tr><td><select class="rowCat" data-mi="${mi}" data-ri="${ri}">${cats.map(c=>`<option ${c===r.cat?'selected':''}>${c}</option>`).join('')}</select></td><td><select class="rowFood" data-mi="${mi}" data-ri="${ri}">${foodOptions(r.cat,r.food)}</select></td><td><input class="qty" data-mi="${mi}" data-ri="${ri}" type="number" value="${r.qty}"></td><td><select class="rowUnit" data-mi="${mi}" data-ri="${ri}"><option ${r.unit==='g'?'selected':''}>g</option><option ${r.unit==='oz'?'selected':''}>oz</option><option ${r.unit==='serving'?'selected':''}>serving</option></select></td><td class="macroCell">${Math.round(m.cal)}</td><td>${m.p.toFixed(1)}g</td><td>${m.c.toFixed(1)}g</td><td>${m.f.toFixed(1)}g</td></tr>`}).join('')}</tbody></table>`;wrap.appendChild(div)});bindRows();totals()}
function bindRows(){document.querySelectorAll('.rowCat').forEach(el=>el.onchange=e=>{let r=state.meals[e.target.dataset.mi][e.target.dataset.ri];r.cat=e.target.value;r.food=(foods.find(f=>f.cat===r.cat)||foods[0]).name;renderMeals()});document.querySelectorAll('.rowFood').forEach(el=>el.onchange=e=>{state.meals[e.target.dataset.mi][e.target.dataset.ri].food=e.target.value;renderMeals()});document.querySelectorAll('.qty').forEach(el=>el.oninput=e=>{state.meals[e.target.dataset.mi][e.target.dataset.ri].qty=e.target.value;totals();renderMeals()});document.querySelectorAll('.rowUnit').forEach(el=>el.onchange=e=>{state.meals[e.target.dataset.mi][e.target.dataset.ri].unit=e.target.value;renderMeals()})}
function totals(){const calTarget=targets();let t={cal:0,p:0,c:0,f:0,sod:0,sugar:0};state.meals.flat().forEach(r=>{const m=calcRow(r);Object.keys(t).forEach(k=>t[k]+=m[k])});$('calTotal').textContent=Math.round(t.cal);$('proTotal').textContent=t.p.toFixed(1)+'g';$('carbTotal').textContent=t.c.toFixed(1)+'g';$('fatTotal').textContent=t.f.toFixed(1)+'g';$('sodTotal').textContent=Math.round(t.sod)+'mg';$('sugarTotal').textContent=t.sugar.toFixed(1)+'g';const flags=[['Calories',t.cal,calTarget,''],['Protein',t.p,num('proteinTarget'),'g'],['Carbs',t.c,num('carbTarget'),'g'],['Fat',t.f,num('fatTarget'),'g'],['Sodium',t.sod,num('sodiumTarget'),'mg']];$('macroFlags').innerHTML=flags.map(([n,a,b,u])=>`<div class="flag ${Math.abs(a-b)<=b*.1?'good':'bad'}">${n}: ${Math.round(a)}${u} / ${Math.round(b)}${u} (${Math.round(a-b)}${u})</div>`).join('')}
function renderDb(){ $('dbList').innerHTML=foods.map(f=>`${f.cat} — <b>${f.name}</b> | ${f.cal} cal P${f.p} C${f.c} F${f.f} per 100g`).join('<br>') }
$('addFood').onclick=()=>{foods.push({name:$('dbName').value||'New Food',cat:$('dbCat').value,cal:num('dbCal'),p:num('dbPro'),c:num('dbCarb'),f:num('dbFat'),sod:0,sugar:0,serv:num('dbServ')||100});renderDb();renderMeals()};
$('saveBtn').onclick=()=>{const data={profile:['clientName','sex','age','height','weight','goalWeight','weeks','activity','goal','notes','proteinTarget','carbTarget','fatTarget','sodiumTarget'].reduce((o,id)=>(o[id]=$(id).value,o),{}),foods,state};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='sclass-client-plan.json';a.click()};
$('importFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const data=JSON.parse(reader.result);Object.entries(data.profile||{}).forEach(([id,v])=>$(id)&&($(id).value=v));if(data.foods)foods=data.foods;if(data.state)state.meals=data.state.meals;renderDb();renderMeals()};reader.readAsText(file)};
['clientName','sex','age','height','weight','goalWeight','weeks','activity','goal','proteinTarget','carbTarget','fatTarget','sodiumTarget'].forEach(id=>$(id).addEventListener('input',totals));
renderDb();renderMeals();
