const cats=['Blank','Protein','Carb','Fat','Vegetable','Fruit','Dairy','Condiment','Other'];
let foods=[
{name:'None / Blank',cat:'Blank',cal:0,p:0,c:0,f:0,fiber:0,sugar:0,sodium:0,serv:100},
{name:'Chicken Breast Raw',cat:'Protein',cal:120,p:23,c:0,f:2.6,fiber:0,sugar:0,sodium:60,serv:100},
{name:'Chicken Breast Cooked',cat:'Protein',cal:165,p:31,c:0,f:3.6,fiber:0,sugar:0,sodium:74,serv:100},
{name:'Egg Whites',cat:'Protein',cal:52,p:11,c:.7,f:.2,fiber:0,sugar:.7,sodium:166,serv:100},
{name:'Greek Yogurt Nonfat',cat:'Dairy',cal:59,p:10,c:3.6,f:.4,fiber:0,sugar:3.2,sodium:36,serv:170},
{name:'Lean Ground Beef 93%',cat:'Protein',cal:172,p:21,c:0,f:8,fiber:0,sugar:0,sodium:75,serv:100},
{name:'Salmon',cat:'Protein',cal:208,p:20,c:0,f:13,fiber:0,sugar:0,sodium:59,serv:100},
{name:'Turkey Breast',cat:'Protein',cal:135,p:30,c:0,f:1,fiber:0,sugar:0,sodium:60,serv:100},
{name:'Tuna',cat:'Protein',cal:132,p:29,c:0,f:1,fiber:0,sugar:0,sodium:47,serv:100},
{name:'Whey Protein',cat:'Protein',cal:120,p:24,c:3,f:1.5,fiber:0,sugar:1,sodium:120,serv:31},
{name:'White Rice Cooked',cat:'Carb',cal:130,p:2.7,c:28,f:.3,fiber:.4,sugar:.1,sodium:1,serv:100},
{name:'Jasmine Rice Cooked',cat:'Carb',cal:129,p:2.7,c:28,f:.3,fiber:.4,sugar:0,sodium:0,serv:100},
{name:'Sweet Potato',cat:'Carb',cal:86,p:1.6,c:20,f:.1,fiber:3,sugar:4.2,sodium:55,serv:100},
{name:'Oats Dry',cat:'Carb',cal:389,p:17,c:66,f:7,fiber:10.6,sugar:1,sodium:2,serv:40},
{name:'Bagel Plain',cat:'Carb',cal:250,p:9,c:48,f:1.5,fiber:2,sugar:6,sodium:430,serv:95},
{name:'Banana',cat:'Fruit',cal:89,p:1.1,c:23,f:.3,fiber:2.6,sugar:12,sodium:1,serv:118},
{name:'Blueberries',cat:'Fruit',cal:57,p:.7,c:14.5,f:.3,fiber:2.4,sugar:10,sodium:1,serv:100},
{name:'Avocado',cat:'Fat',cal:160,p:2,c:9,f:15,fiber:7,sugar:.7,sodium:7,serv:100},
{name:'Peanut Butter',cat:'Fat',cal:588,p:25,c:20,f:50,fiber:6,sugar:9,sodium:17,serv:32},
{name:'Olive Oil',cat:'Fat',cal:884,p:0,c:0,f:100,fiber:0,sugar:0,sodium:2,serv:14},
{name:'Almonds',cat:'Fat',cal:579,p:21,c:22,f:50,fiber:12.5,sugar:4.4,sodium:1,serv:28},
{name:'Broccoli',cat:'Vegetable',cal:35,p:2.4,c:7.2,f:.4,fiber:3.3,sugar:1.4,sodium:41,serv:100},
{name:'Spinach',cat:'Vegetable',cal:23,p:2.9,c:3.6,f:.4,fiber:2.2,sugar:.4,sodium:79,serv:100},
{name:'Asparagus',cat:'Vegetable',cal:20,p:2.2,c:3.9,f:.1,fiber:2.1,sugar:1.9,sodium:2,serv:100},
{name:'Pink Salt 1/4 tsp',cat:'Condiment',cal:0,p:0,c:0,f:0,fiber:0,sugar:0,sodium:575,serv:1.5},
{name:'Sugar Free BBQ Sauce',cat:'Condiment',cal:40,p:0,c:8,f:0,fiber:0,sugar:1,sodium:650,serv:100}
];
const $=id=>document.getElementById(id), qsa=s=>[...document.querySelectorAll(s)], num=id=>parseFloat($(id)?.value)||0;
const state={meals:Array.from({length:6},()=>Array.from({length:7},()=>({cat:'Blank',food:'None / Blank',qty:0,unit:'g'}))),checkins:Array.from({length:12},(_,i)=>({week:i+1,date:'',weight:'',calories:'',adherence:'',notes:''}))};
function setDefaultDates(){const d=new Date(); if(!$('startDate').value)$('startDate').value=d.toISOString().slice(0,10); const t=new Date(d); t.setDate(t.getDate()+112); if(!$('targetDate').value)$('targetDate').value=t.toISOString().slice(0,10)}
function lb(){return $('weightUnit').value==='kg'?num('weight')*2.20462:num('weight')} function goalLb(){return $('weightUnit').value==='kg'?num('goalWeight')*2.20462:num('goalWeight')} function inch(){return $('heightUnit').value==='cm'?num('height')/2.54:num('height')}
function daysBetween(){const a=new Date($('startDate').value),b=new Date($('targetDate').value);return Math.max(7,Math.round((b-a)/86400000)||112)}
function bmr(){const kg=lb()*0.453592, cm=inch()*2.54, age=num('age'); return $('sex').value==='Male'?10*kg+6.25*cm-5*age+5:10*kg+6.25*cm-5*age-161}
function plannedTargets(auto=false){const B=bmr(),T=B*parseFloat($('activity').value), goal=$('goal').value, weeks=daysBetween()/7, weekly=(goalLb()-lb())/weeks; let cal=T;if(goal==='Fat Loss') cal=T-500; if(goal==='Lean Bulk') cal=T+250; if(goal==='Muscle Gain') cal=T+400; if(goal==='Recomp') cal=T-150; if(goal==='Maintain') cal=T; if(auto||!$('calTarget').value) $('calTarget').value=Math.round(cal); if(auto||!$('proteinTarget').value) $('proteinTarget').value=Math.round(lb()*(goal==='Muscle Gain'||goal==='Lean Bulk'?1.05:1)); if(auto||!$('fatTarget').value) $('fatTarget').value=Math.round(lb()*.35); if(auto||!$('carbTarget').value) recalcCarbs(); return {B,T,weeks,weekly,cal:num('calTarget')||cal}}
function recalcCarbs(){const carbs=Math.max(0,Math.round((num('calTarget')-(num('proteinTarget')*4+num('fatTarget')*9))/4)); $('carbTarget').value=carbs}
function grams(q,u,food){if(u==='oz')return q*28.3495;if(u==='serving')return q*(food.serv||100);return q}
function macroFor(row){const food=foods.find(f=>f.name===row.food)||foods[0], g=grams(parseFloat(row.qty)||0,row.unit,food), m=g/100; return {cal:food.cal*m,p:food.p*m,c:food.c*m,f:food.f*m,fiber:(food.fiber||0)*m,sugar:(food.sugar||0)*m,sodium:(food.sodium||0)*m,grams:g,food}}
function totals(){let t={cal:0,p:0,c:0,f:0,fiber:0,sugar:0,sodium:0}; state.meals.flat().forEach(r=>{const m=macroFor(r); Object.keys(t).forEach(k=>t[k]+=m[k])}); return t}
function options(arr,val){return arr.map(x=>`<option ${String(x)===String(val)?'selected':''}>${x}</option>`).join('')} function foodOptions(cat,val){return foods.filter(f=>f.cat===cat).sort((a,b)=>a.name.localeCompare(b.name)).map(f=>`<option ${f.name===val?'selected':''}>${f.name}</option>`).join('')}
function renderMeals(){const wrap=$('meals'); wrap.innerHTML=''; state.meals.forEach((meal,mi)=>{let mt={cal:0,p:0,c:0,f:0}; meal.forEach(r=>{const m=macroFor(r); mt.cal+=m.cal;mt.p+=m.p;mt.c+=m.c;mt.f+=m.f}); const div=document.createElement('div'); div.className='meal'; div.innerHTML=`<div class="mealHeader"><h3>Meal ${mi+1}</h3><div class="mealTotals">${Math.round(mt.cal)} cal • P ${mt.p.toFixed(1)} • C ${mt.c.toFixed(1)} • F ${mt.f.toFixed(1)}</div></div><div class="tableWrap"><table><thead><tr><th>Category</th><th>Item</th><th>Amount</th><th>Unit</th><th>Grams</th><th>Cal</th><th>Protein</th><th>Carbs</th><th>Fat</th><th>Fiber</th><th>Sugar</th><th>Sodium</th></tr></thead><tbody>${meal.map((r,ri)=>{const m=macroFor(r);return `<tr><td><select class="catSel" data-mi="${mi}" data-ri="${ri}">${options(cats,r.cat)}</select></td><td><select class="foodSel" data-mi="${mi}" data-ri="${ri}">${foodOptions(r.cat,r.food)}</select></td><td><input class="qty" data-mi="${mi}" data-ri="${ri}" type="number" step=".1" value="${r.qty}"></td><td><select class="unitSel" data-mi="${mi}" data-ri="${ri}">${options(['g','oz','serving'],r.unit)}</select></td><td>${m.grams.toFixed(0)}g</td><td class="macro">${Math.round(m.cal)}</td><td>${m.p.toFixed(1)}</td><td>${m.c.toFixed(1)}</td><td>${m.f.toFixed(1)}</td><td>${m.fiber.toFixed(1)}</td><td>${m.sugar.toFixed(1)}</td><td>${Math.round(m.sodium)}</td></tr>`}).join('')}</tbody></table></div>`; wrap.appendChild(div)}); bindMealEvents(); updateAll(false)}
function bindMealEvents(){qsa('.catSel').forEach(e=>e.onchange=ev=>{const r=state.meals[ev.target.dataset.mi][ev.target.dataset.ri]; r.cat=ev.target.value; r.food=(foods.find(f=>f.cat===r.cat)||foods[0]).name; renderMeals()});qsa('.foodSel').forEach(e=>e.onchange=ev=>{state.meals[ev.target.dataset.mi][ev.target.dataset.ri].food=ev.target.value; renderMeals()});qsa('.qty').forEach(e=>e.oninput=ev=>{state.meals[ev.target.dataset.mi][ev.target.dataset.ri].qty=ev.target.value; updateAll(false)});qsa('.unitSel').forEach(e=>e.onchange=ev=>{state.meals[ev.target.dataset.mi][ev.target.dataset.ri].unit=ev.target.value; renderMeals()})}
function renderBars(t){const items=[['Calories',t.cal,num('calTarget'),''],['Protein',t.p,num('proteinTarget'),'g'],['Carbs',t.c,num('carbTarget'),'g'],['Fat',t.f,num('fatTarget'),'g'],['Fiber',t.fiber,num('fiberTarget'),'g'],['Sugar',t.sugar,num('sugarTarget'),'g max'],['Sodium',t.sodium,num('sodiumTarget'),'mg']]; $('macroBars').innerHTML=items.map(([n,a,b,u])=>{const pct=b?Math.min(160,a/b*100):0, over=a>b*1.1; return `<div class="barRow"><b>${n}</b><div class="barTrack"><div class="barFill ${over?'over':''}" style="width:${Math.min(100,pct)}%"></div></div><span class="${Math.abs(a-b)<=b*.1?'flagGood':over?'flagBad':''}">${Math.round(a)} / ${Math.round(b)} ${u}</span></div>`}).join('')}
function renderSnapshot(p,t){const accuracy=macroAccuracy(t); $('coachSnapshot').innerHTML=`<div><b>Goal:</b> ${$('goal').value}</div><div><b>Activity:</b> ${$('activity').selectedOptions[0].text}</div><div><b>Goal Pace:</b> ${p.weekly.toFixed(2)} lb/week</div><div><b>Calories:</b> ${Math.round(t.cal)} planned vs ${num('calTarget')} target</div><div><b>Protein:</b> ${t.p.toFixed(1)}g planned vs ${num('proteinTarget')}g target</div><div><b>Accuracy:</b> ${accuracy}%</div>`}
function macroAccuracy(t){const diffs=[Math.abs(t.cal-num('calTarget'))/(num('calTarget')||1),Math.abs(t.p-num('proteinTarget'))/(num('proteinTarget')||1),Math.abs(t.c-num('carbTarget'))/(num('carbTarget')||1),Math.abs(t.f-num('fatTarget'))/(num('fatTarget')||1)]; return Math.max(0,Math.round(100-(diffs.reduce((a,b)=>a+b,0)/diffs.length*100)))}
function renderRanges(){const w=lb(); $('rangeGrid').innerHTML=[`Protein<br><b>${Math.round(w*.8)}–${Math.round(w*1.15)}g</b>`,`Fat<br><b>${Math.round(w*.25)}–${Math.round(w*.45)}g</b>`,`Fiber<br><b>25–40g</b>`,`Sodium<br><b>2,000–3,500mg*</b>`,`Cut Pace<br><b>0.5–1.5 lb/week</b>`,`Aggressive Cut<br><b>2+ lb/week</b>`,`Lean Bulk<br><b>0.25–0.5 lb/week</b>`,`Water<br><b>${Math.round(w*.55)}–${Math.round(w*.75)} oz</b>`].map(x=>`<div>${x}</div>`).join('')}
function renderCheckins(){let last=''; $('checkRows').innerHTML=state.checkins.map((r,i)=>{const change=(r.weight&&last)?(parseFloat(r.weight)-parseFloat(last)).toFixed(1):''; if(r.weight)last=r.weight; return `<tr><td>${r.week}</td><td><input type="date" data-c="date" data-i="${i}" value="${r.date}"></td><td><input type="number" data-c="weight" data-i="${i}" value="${r.weight}"></td><td>${change}</td><td><input type="number" data-c="calories" data-i="${i}" value="${r.calories}"></td><td><input type="number" data-c="adherence" data-i="${i}" value="${r.adherence}"></td><td><input data-c="notes" data-i="${i}" value="${r.notes}"></td></tr>`}).join(''); qsa('#checkRows input').forEach(e=>e.oninput=ev=>{state.checkins[ev.target.dataset.i][ev.target.dataset.c]=ev.target.value})}
function renderFoodDb(){ $('newFoodCat').innerHTML=options(cats,'Protein'); foods.sort((a,b)=>a.cat.localeCompare(b.cat)||a.name.localeCompare(b.name)); $('foodTable').innerHTML=foods.map(f=>`<tr><td>${f.cat}</td><td><b>${f.name}</b></td><td>${f.cal}</td><td>${f.p}</td><td>${f.c}</td><td>${f.f}</td><td>${f.fiber||0}</td><td>${f.sugar||0}</td><td>${f.sodium||0}</td><td>${f.serv||100}g</td></tr>`).join('')}
function renderExport(t){$('clientMeta').innerHTML=[['Client',$('clientName').value],['Goal',$('goal').value],['Current Weight',num('weight')+' '+$('weightUnit').value],['Goal Weight',num('goalWeight')+' '+$('weightUnit').value],['Start',$('startDate').value],['Target',$('targetDate').value],['Activity',$('activity').selectedOptions[0].text],['Training Days',num('trainingDays')]].map(([a,b])=>`<div><b>${a}</b><br>${b}</div>`).join(''); $('exportTargets').innerHTML=[['Calories',num('calTarget')],['Protein',num('proteinTarget')+'g'],['Carbs',num('carbTarget')+'g'],['Fat',num('fatTarget')+'g'],['Fiber',num('fiberTarget')+'g'],['Sugar Max',num('sugarTarget')+'g'],['Sodium',num('sodiumTarget')+'mg'],['Water',num('waterTarget')+' oz']].map(([a,b])=>`<div><b>${a}</b><br>${b}</div>`).join(''); $('exportNotes').textContent=$('coachNotes').value||'No notes added.'; $('exportMeals').innerHTML=state.meals.map((meal,mi)=>`<div class="exportMeal"><h3>Meal ${mi+1}</h3><table><thead><tr><th>Food</th><th>Amount</th><th>Unit</th><th>Cal</th><th>P</th><th>C</th><th>F</th></tr></thead><tbody>${meal.filter(r=>r.cat!=='Blank'&&parseFloat(r.qty)>0).map(r=>{const m=macroFor(r);return `<tr><td>${r.food}</td><td>${r.qty}</td><td>${r.unit}</td><td>${Math.round(m.cal)}</td><td>${m.p.toFixed(1)}</td><td>${m.c.toFixed(1)}</td><td>${m.f.toFixed(1)}</td></tr>`}).join('')||'<tr><td colspan="7">Blank</td></tr>'}</tbody></table></div>`).join('')}
function updateAll(doTargets=true){const p=plannedTargets(false), t=totals(), acc=macroAccuracy(t); $('bmrOut').textContent=Math.round(p.B); $('tdeeOut').textContent=Math.round(p.T); $('weeklyPaceOut').textContent=p.weekly.toFixed(2)+' lb/wk'; $('accuracyOut').textContent=acc+'%'; $('topCals').textContent=num('calTarget'); $('topActual').textContent=Math.round(t.cal); $('topStatus').textContent=acc>=90?'On Target':acc>=75?'Close':'Adjust'; $('sideClientName').textContent=$('clientName').value||'Client'; $('sideGoal').textContent=$('goal').value; const pace=Math.abs(p.weekly); $('paceStatus').textContent= pace>2 ? `Aggressive pace: ${p.weekly.toFixed(2)} lb/week. Consider longer timeframe or a smaller deficit/surplus.` : `Reasonable pace: ${p.weekly.toFixed(2)} lb/week based on selected dates and goal.`; renderBars(t); renderSnapshot(p,t); renderRanges(); renderExport(t)}
function addFood(){foods.push({name:$('newFoodName').value||'New Food',cat:$('newFoodCat').value,cal:num('newFoodCal'),p:num('newFoodP'),c:num('newFoodC'),f:num('newFoodF'),fiber:num('newFoodFiber'),sugar:num('newFoodSugar'),sodium:num('newFoodSodium'),serv:num('newFoodServing')||100}); renderFoodDb(); renderMeals()}
function exportJson(){const ids=['clientName','sex','age','height','heightUnit','weight','weightUnit','goalWeight','startDate','targetDate','activity','goal','trainingDays','steps','sleepGoal','coachNotes','calTarget','proteinTarget','carbTarget','fatTarget','fiberTarget','sugarTarget','sodiumTarget','waterTarget']; const data={version:'Sclass static Excel-style v2',fields:Object.fromEntries(ids.map(id=>[id,$(id).value])),foods,state}; const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})); a.download=($('clientName').value||'sclass-client').replaceAll(' ','-').toLowerCase()+'.json'; a.click()}
function importJson(file){const r=new FileReader(); r.onload=()=>{const d=JSON.parse(r.result); Object.entries(d.fields||{}).forEach(([id,v])=>$(id)&&($(id).value=v)); if(d.foods)foods=d.foods; if(d.state){state.meals=d.state.meals||state.meals; state.checkins=d.state.checkins||state.checkins} renderFoodDb(); renderCheckins(); renderMeals(); updateAll(false)}; r.readAsText(file)}
qsa('.nav').forEach(btn=>btn.onclick=()=>{qsa('.nav').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); qsa('.view').forEach(v=>v.classList.remove('active')); $(btn.dataset.view).classList.add('active'); updateAll(false)});
['clientName','sex','age','height','heightUnit','weight','weightUnit','goalWeight','startDate','targetDate','activity','goal','trainingDays','steps','sleepGoal','coachNotes','calTarget','proteinTarget','carbTarget','fatTarget','fiberTarget','sugarTarget','sodiumTarget','waterTarget'].forEach(id=>$(id).addEventListener('input',()=>updateAll(false)));
$('autoMacros').onclick=()=>{plannedTargets(true); updateAll(false)}; $('lockTargets').onclick=()=>{recalcCarbs(); updateAll(false)}; $('addFood').onclick=addFood; $('downloadJson').onclick=exportJson; $('importJson').onchange=e=>e.target.files[0]&&importJson(e.target.files[0]);
setDefaultDates(); renderFoodDb(); renderCheckins(); plannedTargets(true); renderMeals(); updateAll(false);
